### ISSUE TITLE
Application does not terminate when Return Key is pressed

### ISSUE THREAD

**Issue by 24santoshr** [delphi-hub/delphi-webapi#22]
**Describe the bug**
WebApi does not terminate when the user presses the 'Return Key' in console. 

**To Reproduce**
1. Start the WebApi application with sbt run
2. The application is started
3. Press the Return Key to terminate the application
4. The Application hangs

**Expected behavior**
The Application should be terminated.

**Comment by bhermann** [comment]
I had a quick look. Well it seems I never implemented that... :flushed:
Will attach actor system termination to server stop.

**Comment by bhermann** [comment]
Solved with 2324c22

**Comment by bhermann** [comment]
Solved with 2324c22

**Comment by bhermann** [comment]
Solved with 2324c226bff6797dc0b467fafc2e47a3247cb80a
