### ISSUE TITLE
Search API provides internal on elastic search errors

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-webapi#34]
**Describe the bug**
When a query fails the error is returned in the result to the client.

**To Reproduce**
1. Produce a search query with a limit > 10000.
2. The resulting ElasticError is just passed along.

**Expected behavior**
Hide unknown errors and give reasonable messages for other cases (e.g. request window (`limit`) set too high)

**Screenshots**
n/a

**Affected components (if known)**
webapi, cli

**Desktop (please complete the following information, if relevant):**
n/a

**Smartphone (please complete the following information, if relevant):**
n/a

**Additional context**
none

**Comment by bhermann** [comment]
@hariharansrc What is the status of this? If this is still open, can you work on this please?

**Comment by johannesduesing** [comment]
Closed with #59
