### ISSUE TITLE
Triggered execution of sbt run

### ISSUE THREAD

**Issue by hariharansrc** [delphi-hub/delphi-webapi#39]
**Is your feature request related to a problem? Please describe.**
Currently sbt process and application process are same.
When application is exited sbt will be killed.
Run sbt separately such that we don't need to wait for sbt load for every run.

**Describe the solution you'd like**
Fork the application process for every run. It is available in sbt.version=1.1.1, but there is command line issue when exiting the application.  In sbt.version=1.2.7 it is working well.

**Describe alternatives you've considered**
There is plugin named https://github.com/spray/sbt-revolver. Need to evaluate whether it adds any thing extra.

**Additional context**
NA

**Comment by hariharansrc** [comment]
To run using triggered execution
1. Run sbt
```
sbt
```
2.  Triggered execution
```
~run
```
3. Application can be exited normally by pressing `Enter`. New changes will be compiled and application starts again.

**Comment by bhermann** [comment]
Closed with #40
